### PR TITLE
Unite the tribes

### PR DESCRIPTION
**Pull request by jacobrosenthal**

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
I incremented npm version off of original so we can just move over to my version. Need to pull my package.json out of this before we merge. Anything else anyone can think of?

**Comment by jacobrosenthal** [comment]
Need to decide what to do with demo. Needs to be updated as its surely been broken or removed.

**Comment by garrows** [comment]
Looks like you got about everything.
I'll add you to the demo too so you can publish it on the chrome webstore soon.

**Comment by phated** [comment]
I think the package.json changes should be rebased out of the history.

**Comment by jacobrosenthal** [comment]
You wanna handle that then?

**Comment by jacobrosenthal** [comment]
Alright got the rebase worked out. @garrows can you add @phated

**Comment by jacobrosenthal** [comment]
Closed in another PR

**Comment by garrows** [comment]
Added @phated. I think you should have access to add people too @jacobrosenthal

**Pull request closed without merging**
