### PR TITLE
Included mention of NW.js as another target platform

### PR DESCRIPTION
**Pull request by cotejp**

### CODE REVIEW

**Comment by garrows** [comment]
Wow, does this actually work out of the box? Have you got an example app?

**Comment by cotejp** [comment]
Yes, it does! It's pretty amazing. In fact, NW.js v0.13+ supports, right out of the box, all the `chrome.*` APIs. This includes `chrome.serial` but other cools ones like `chrome.bluetooth`, `chrome.tts` (text-to-speech), etc.

I'm in a bit of a rush so I cannot send you an example right away. However, I can tell you that with a one-line modification to the firmata and johnny-five modules, I was able to run Johnny-Five inside NW.js. If you are curious, you can check out the pull request I submitted to the firmata project (https://github.com/jgautier/firmata/pull/108). Once it's merged in, I'll do the same for Johnny-Five. 

With those two super simple changes, we will have a kickass and super easy platform for robotics and physical computing.

**Comment by garrows** [comment]
Well that's very impressive. Let me know if you start any cool open source projects with this. I'm sure a few people here will want to help out.

**Comment by cotejp** [comment]
Cool! My current "project" is creating some buzz around the idea that JavaScript is an excellent framework for physical computing. Just as good, if not better, than Processing, OpenFrameworks, Pure-Data, etc. This is the reason I started [tangiblejs.com](http://tangiblejs.com).

The combination of NW.js v0.13 + Johnny-Five + Firmata + browser-serialport has got a huge, and I mean HUGE, potential! Thanks a lot for contributing browser-serialport to the community!!

Cheers!

**Pull request merged**
